
apiVersion: v1
kind: ReplicationController
metadata:
  name: "rc1"

spec:
  replicas: 5
  selector:
    app: web
  template:
    metadata:
      name: "p1"
      labels:
        app: web
    spec:
      containers:
        - name: "c1"
          image: "vimal13/apache-webserver-php"
