apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myd"

spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: "wpod"
      labels:
        env: prod
    spec:
      volumes:
        - name: mypod-pvc
          persistentVolumeClaim:
            claimName: mypvc  
      
      containers:
        - name: "c1"
          image: "devendra618/httpd:v2"
          volumeMounts:
            - name: mypod-pvc
              mountPath: /var/www/html

