apiVersion: networking.k8s.io/v1
kind: NetworkingPolicy
metadata:
        name: myfirewall

spec:
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 85
  podSelector:
    matchLebels:
      app: myd
