apiVersion: v1
kind: Pod
metadata:
  name: "p1"
  labels:
    app: dev
spec:
  containers:
    - name: "c1"
      image: "mysql:5.7"
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret1
              key: p
        - name: MYSQL_DATABASE
          value: WP
        - name: MYSQL_USER
          value: dev
        - name: MYSQL_PASSWORD
          value: redha

