apiVersion: v1
kind: PersistentVolume
metadata: 
  name: "pv1"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: "192.168.0.129" 
    path: "/mydata"
